name: Demo Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "development" ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        run: |
          echo "patch_version=`expr ${{ github.run_number }} % 10`" >> "$GITHUB_ENV"
          echo "minor_version=`expr ${{ github.run_number }} / 10`" >> "$GITHUB_ENV"
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$patch_version"
          printf '%s\n' "$minor_version"

      - name: Build image
        run: docker build .

      - run: echo This event is a pull request.
        if: ${{ github.event_name == 'pull_request' }}
      - run: echo This event is a push.
        if: ${{ github.event_name == 'push' }}

