name: Demo Push

on:
  pull_request:
    branches:
      - development
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set the value
        id: step_one
        run: |
          echo "patch_version=`expr ${{ github.run_number }} / 10`" >> "$GITHUB_ENV"
      - name: Use the value
        id: step_two
        run: |
          printf '%s\n' "$patch_version"

      - name: Build image
        run: docker build .
