name: Demo Push

on:
  pull_request:
    branches:
      - development
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: run number with offset
        env:
          NUM: ${{ github.run_number }}
        run: |
          echo ::set-env name=GITHUB_RUN_NUMBER_WITH_OFFSET::$(($NUM+200))
      - run: echo $GITHUB_RUN_NUMBER_WITH_OFFSET

      - name: Build image
        run: docker build .
