name: Demo Push

on:
  pull_request:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME:${GITHUB_RUN_ID} --label "runnumber=${GITHUB_RUN_ID}"
